#include "InputGate.hpp"
#include "OutputGate.hpp"

#include "AndGate.hpp"
#include "NAndGate.hpp"
#include "NegateGate.hpp"
#include "NOrGate.hpp"
#include "NXOrGate.hpp"
#include "OrGate.hpp"
#include "XOrGate.hpp"
